//
// Generated by sedonac 1.2.28
// 27-Oct-2025 07:17
//

#include "sedona.h"

////////////////////////////////////////////////////////////////
// sys (kitId=0)
////////////////////////////////////////////////////////////////

// sys::Str Sys.platformType()
Cell sys_Sys_platformType(SedonaVM* vm, Cell* params);

// void Sys.copy(byte[], int, byte[], int, int)
Cell sys_Sys_copy(SedonaVM* vm, Cell* params);

// byte[] Sys.malloc(int)
Cell sys_Sys_malloc(SedonaVM* vm, Cell* params);

// void Sys.free(sys::Obj)
Cell sys_Sys_free(SedonaVM* vm, Cell* params);

// sys::Str Sys.intStr(int)
Cell sys_Sys_intStr(SedonaVM* vm, Cell* params);

// sys::Str Sys.hexStr(int)
Cell sys_Sys_hexStr(SedonaVM* vm, Cell* params);

// sys::Str Sys.longStr(long)
Cell sys_Sys_longStr(SedonaVM* vm, Cell* params);

// sys::Str Sys.longHexStr(long)
Cell sys_Sys_longHexStr(SedonaVM* vm, Cell* params);

// sys::Str Sys.floatStr(float)
Cell sys_Sys_floatStr(SedonaVM* vm, Cell* params);

// sys::Str Sys.doubleStr(double)
Cell sys_Sys_doubleStr(SedonaVM* vm, Cell* params);

// int Sys.floatToBits(float)
Cell sys_Sys_floatToBits(SedonaVM* vm, Cell* params);

// long Sys.doubleToBits(double)
Cell sys_Sys_doubleToBits(SedonaVM* vm, Cell* params);

// float Sys.bitsToFloat(int)
Cell sys_Sys_bitsToFloat(SedonaVM* vm, Cell* params);

// double Sys.bitsToDouble(long)
Cell sys_Sys_bitsToDouble(SedonaVM* vm, Cell* params);

// long Sys.ticks()
Cell sys_Sys_ticks(SedonaVM* vm, Cell* params);

// void Sys.sleep(long)
Cell sys_Sys_sleep(SedonaVM* vm, Cell* params);

// int Sys.compareBytes(byte[], int, byte[], int, int)
Cell sys_Sys_compareBytes(SedonaVM* vm, Cell* params);

// void Sys.setBytes(int, byte[], int, int)
Cell sys_Sys_setBytes(SedonaVM* vm, Cell* params);

// void Sys.andBytes(int, byte[], int, int)
Cell sys_Sys_andBytes(SedonaVM* vm, Cell* params);

// void Sys.orBytes(int, byte[], int, int)
Cell sys_Sys_orBytes(SedonaVM* vm, Cell* params);

// byte[] Sys.scodeAddr()
Cell sys_Sys_scodeAddr(SedonaVM* vm, Cell* params);

// int Sys.rand()
Cell sys_Sys_rand(SedonaVM* vm, Cell* params);

// void Component.invokeVoid(sys::Slot)
Cell sys_Component_invokeVoid(SedonaVM* vm, Cell* params);

// void Component.invokeBool(sys::Slot, bool)
Cell sys_Component_invokeBool(SedonaVM* vm, Cell* params);

// void Component.invokeInt(sys::Slot, int)
Cell sys_Component_invokeInt(SedonaVM* vm, Cell* params);

// void Component.invokeLong(sys::Slot, long)
Cell sys_Component_invokeLong(SedonaVM* vm, Cell* params);

// void Component.invokeFloat(sys::Slot, float)
Cell sys_Component_invokeFloat(SedonaVM* vm, Cell* params);

// void Component.invokeDouble(sys::Slot, double)
Cell sys_Component_invokeDouble(SedonaVM* vm, Cell* params);

// void Component.invokeBuf(sys::Slot, sys::Buf)
Cell sys_Component_invokeBuf(SedonaVM* vm, Cell* params);

// bool Component.getBool(sys::Slot)
Cell sys_Component_getBool(SedonaVM* vm, Cell* params);

// int Component.getInt(sys::Slot)
Cell sys_Component_getInt(SedonaVM* vm, Cell* params);

// long Component.getLong(sys::Slot)
Cell sys_Component_getLong(SedonaVM* vm, Cell* params);

// float Component.getFloat(sys::Slot)
Cell sys_Component_getFloat(SedonaVM* vm, Cell* params);

// double Component.getDouble(sys::Slot)
Cell sys_Component_getDouble(SedonaVM* vm, Cell* params);

// sys::Buf Component.getBuf(sys::Slot)
Cell sys_Component_getBuf(SedonaVM* vm, Cell* params);

// bool Component.doSetBool(sys::Slot, bool)
Cell sys_Component_doSetBool(SedonaVM* vm, Cell* params);

// bool Component.doSetInt(sys::Slot, int)
Cell sys_Component_doSetInt(SedonaVM* vm, Cell* params);

// bool Component.doSetLong(sys::Slot, long)
Cell sys_Component_doSetLong(SedonaVM* vm, Cell* params);

// bool Component.doSetFloat(sys::Slot, float)
Cell sys_Component_doSetFloat(SedonaVM* vm, Cell* params);

// bool Component.doSetDouble(sys::Slot, double)
Cell sys_Component_doSetDouble(SedonaVM* vm, Cell* params);

// sys::Obj Type.malloc()
Cell sys_Type_malloc(SedonaVM* vm, Cell* params);

// bool StdOutStream.doWrite(int)
Cell sys_StdOutStream_doWrite(SedonaVM* vm, Cell* params);

// bool StdOutStream.doWriteBytes(byte[], int, int)
Cell sys_StdOutStream_doWriteBytes(SedonaVM* vm, Cell* params);

// void StdOutStream.doFlush()
Cell sys_StdOutStream_doFlush(SedonaVM* vm, Cell* params);

// int FileStore.doSize(sys::Str)
Cell sys_FileStore_doSize(SedonaVM* vm, Cell* params);

// sys::Obj FileStore.doOpen(sys::Str, sys::Str)
Cell sys_FileStore_doOpen(SedonaVM* vm, Cell* params);

// int FileStore.doRead(sys::Obj)
Cell sys_FileStore_doRead(SedonaVM* vm, Cell* params);

// int FileStore.doReadBytes(sys::Obj, byte[], int, int)
Cell sys_FileStore_doReadBytes(SedonaVM* vm, Cell* params);

// bool FileStore.doWrite(sys::Obj, int)
Cell sys_FileStore_doWrite(SedonaVM* vm, Cell* params);

// bool FileStore.doWriteBytes(sys::Obj, byte[], int, int)
Cell sys_FileStore_doWriteBytes(SedonaVM* vm, Cell* params);

// int FileStore.doTell(sys::Obj)
Cell sys_FileStore_doTell(SedonaVM* vm, Cell* params);

// bool FileStore.doSeek(sys::Obj, int)
Cell sys_FileStore_doSeek(SedonaVM* vm, Cell* params);

// void FileStore.doFlush(sys::Obj)
Cell sys_FileStore_doFlush(SedonaVM* vm, Cell* params);

// bool FileStore.doClose(sys::Obj)
Cell sys_FileStore_doClose(SedonaVM* vm, Cell* params);

// bool FileStore.rename(sys::Str, sys::Str)
Cell sys_FileStore_rename(SedonaVM* vm, Cell* params);

// int Test.doMain()
Cell sys_Test_doMain(SedonaVM* vm, Cell* params);

// sys::Str Str.fromBytes(byte[], int)
Cell sys_Str_fromBytes(SedonaVM* vm, Cell* params);

// sys::Str PlatformService.doPlatformId()
Cell sys_PlatformService_doPlatformId(SedonaVM* vm, Cell* params);

// sys::Str PlatformService.getPlatVersion()
Cell sys_PlatformService_getPlatVersion(SedonaVM* vm, Cell* params);

// long PlatformService.getNativeMemAvailable()
Cell sys_PlatformService_getNativeMemAvailable(SedonaVM* vm, Cell* params);

// native table for kit 0
NativeMethod kitNatives0[] = 
{
  sys_Sys_platformType,           // 0::0
  sys_Sys_copy,                   // 0::1
  sys_Sys_malloc,                 // 0::2
  sys_Sys_free,                   // 0::3
  sys_Sys_intStr,                 // 0::4
  sys_Sys_hexStr,                 // 0::5
  sys_Sys_longStr,                // 0::6
  sys_Sys_longHexStr,             // 0::7
  sys_Sys_floatStr,               // 0::8
  sys_Sys_doubleStr,              // 0::9
  sys_Sys_floatToBits,            // 0::10
  sys_Sys_doubleToBits,           // 0::11
  sys_Sys_bitsToFloat,            // 0::12
  sys_Sys_bitsToDouble,           // 0::13
  sys_Sys_ticks,                  // 0::14
  sys_Sys_sleep,                  // 0::15
  sys_Sys_compareBytes,           // 0::16
  sys_Sys_setBytes,               // 0::17
  sys_Sys_andBytes,               // 0::18
  sys_Sys_orBytes,                // 0::19
  sys_Sys_scodeAddr,              // 0::20
  sys_Sys_rand,                   // 0::21
  sys_Component_invokeVoid,       // 0::22
  sys_Component_invokeBool,       // 0::23
  sys_Component_invokeInt,        // 0::24
  sys_Component_invokeLong,       // 0::25
  sys_Component_invokeFloat,      // 0::26
  sys_Component_invokeDouble,     // 0::27
  sys_Component_invokeBuf,        // 0::28
  sys_Component_getBool,          // 0::29
  sys_Component_getInt,           // 0::30
  sys_Component_getLong,          // 0::31
  sys_Component_getFloat,         // 0::32
  sys_Component_getDouble,        // 0::33
  sys_Component_getBuf,           // 0::34
  sys_Component_doSetBool,        // 0::35
  sys_Component_doSetInt,         // 0::36
  sys_Component_doSetLong,        // 0::37
  sys_Component_doSetFloat,       // 0::38
  sys_Component_doSetDouble,      // 0::39
  sys_Type_malloc,                // 0::40
  sys_StdOutStream_doWrite,       // 0::41
  sys_StdOutStream_doWriteBytes,  // 0::42
  sys_StdOutStream_doFlush,       // 0::43
  sys_FileStore_doSize,           // 0::44
  sys_FileStore_doOpen,           // 0::45
  sys_FileStore_doRead,           // 0::46
  sys_FileStore_doReadBytes,      // 0::47
  sys_FileStore_doWrite,          // 0::48
  sys_FileStore_doWriteBytes,     // 0::49
  sys_FileStore_doTell,           // 0::50
  sys_FileStore_doSeek,           // 0::51
  sys_FileStore_doFlush,          // 0::52
  sys_FileStore_doClose,          // 0::53
  sys_FileStore_rename,           // 0::54
  sys_Test_doMain,                // 0::55
  sys_Str_fromBytes,              // 0::56
  sys_PlatformService_doPlatformId,  // 0::57
  sys_PlatformService_getPlatVersion,  // 0::58
  sys_PlatformService_getNativeMemAvailable,  // 0::59
};

////////////////////////////////////////////////////////////////
// inet (kitId=2)
////////////////////////////////////////////////////////////////

// bool TcpSocket.connect(inet::IpAddr, int)
Cell inet_TcpSocket_connect(SedonaVM* vm, Cell* params);

// bool TcpSocket.finishConnect()
Cell inet_TcpSocket_finishConnect(SedonaVM* vm, Cell* params);

// int TcpSocket.write(byte[], int, int)
Cell inet_TcpSocket_write(SedonaVM* vm, Cell* params);

// int TcpSocket.read(byte[], int, int)
Cell inet_TcpSocket_read(SedonaVM* vm, Cell* params);

// void TcpSocket.close()
Cell inet_TcpSocket_close(SedonaVM* vm, Cell* params);

// bool TcpServerSocket.bind(int)
Cell inet_TcpServerSocket_bind(SedonaVM* vm, Cell* params);

// bool TcpServerSocket.accept(inet::TcpSocket)
Cell inet_TcpServerSocket_accept(SedonaVM* vm, Cell* params);

// void TcpServerSocket.close()
Cell inet_TcpServerSocket_close(SedonaVM* vm, Cell* params);

// bool UdpSocket.open()
Cell inet_UdpSocket_open(SedonaVM* vm, Cell* params);

// bool UdpSocket.bind(int)
Cell inet_UdpSocket_bind(SedonaVM* vm, Cell* params);

// bool UdpSocket.send(inet::UdpDatagram)
Cell inet_UdpSocket_send(SedonaVM* vm, Cell* params);

// bool UdpSocket.receive(inet::UdpDatagram)
Cell inet_UdpSocket_receive(SedonaVM* vm, Cell* params);

// void UdpSocket.close()
Cell inet_UdpSocket_close(SedonaVM* vm, Cell* params);

// int UdpSocket.maxPacketSize()
Cell inet_UdpSocket_maxPacketSize(SedonaVM* vm, Cell* params);

// int UdpSocket.idealPacketSize()
Cell inet_UdpSocket_idealPacketSize(SedonaVM* vm, Cell* params);

// void Crypto.sha1(byte[], int, int, byte[], int)
Cell inet_Crypto_sha1(SedonaVM* vm, Cell* params);

// bool UdpSocket.join()
Cell inet_UdpSocket_join(SedonaVM* vm, Cell* params);

// native table for kit 2
NativeMethod kitNatives2[] = 
{
  inet_TcpSocket_connect,         // 2::0
  inet_TcpSocket_finishConnect,   // 2::1
  inet_TcpSocket_write,           // 2::2
  inet_TcpSocket_read,            // 2::3
  inet_TcpSocket_close,           // 2::4
  inet_TcpServerSocket_bind,      // 2::5
  inet_TcpServerSocket_accept,    // 2::6
  inet_TcpServerSocket_close,     // 2::7
  inet_UdpSocket_open,            // 2::8
  inet_UdpSocket_bind,            // 2::9
  inet_UdpSocket_send,            // 2::10
  inet_UdpSocket_receive,         // 2::11
  inet_UdpSocket_close,           // 2::12
  inet_UdpSocket_maxPacketSize,   // 2::13
  inet_UdpSocket_idealPacketSize,  // 2::14
  inet_Crypto_sha1,               // 2::15
  inet_UdpSocket_join,            // 2::16
};

////////////////////////////////////////////////////////////////
// EacIo (kitId=4)
////////////////////////////////////////////////////////////////

// bool boolInPoint.get(int)
Cell EacIo_boolInPoint_get(SedonaVM* vm, Cell* params);

// bool boolOutPoint.set(int, bool)
Cell EacIo_boolOutPoint_set(SedonaVM* vm, Cell* params);

// bool binaryValuePoint.set(int, bool)
Cell EacIo_binaryValuePoint_set(SedonaVM* vm, Cell* params);

// float analogInPoint.get(int)
Cell EacIo_analogInPoint_get(SedonaVM* vm, Cell* params);

// bool analogOutPoint.set(int, float)
Cell EacIo_analogOutPoint_set(SedonaVM* vm, Cell* params);

// bool analogValuePoint.set(int, float)
Cell EacIo_analogValuePoint_set(SedonaVM* vm, Cell* params);

// int eacio.resolveChannel(sys::Str)
Cell EacIo_eacio_resolveChannel(SedonaVM* vm, Cell* params);

// int eacio.getRecordCount(sys::Str)
Cell EacIo_eacio_getRecordCount(SedonaVM* vm, Cell* params);

// bool eacio.getCurStatus(int, sys::Str)
Cell EacIo_eacio_getCurStatus(SedonaVM* vm, Cell* params);

// bool eacio.getChannelName(int, sys::Str)
Cell EacIo_eacio_getChannelName(SedonaVM* vm, Cell* params);

// bool triacPoint.set(int, bool)
Cell EacIo_triacPoint_set(SedonaVM* vm, Cell* params);

// int eacio.writeSedonaId(int, int)
Cell EacIo_eacio_writeSedonaId(SedonaVM* vm, Cell* params);

// int eacio.writeSedonaType(int, sys::Str, sys::Str)
Cell EacIo_eacio_writeSedonaType(SedonaVM* vm, Cell* params);

// bool eacio.isChannelEnabled(int)
Cell EacIo_eacio_isChannelEnabled(SedonaVM* vm, Cell* params);

// bool eacio.getBoolTagValue(int, sys::Str)
Cell EacIo_eacio_getBoolTagValue(SedonaVM* vm, Cell* params);

// float eacio.getNumberTagValue(int, sys::Str)
Cell EacIo_eacio_getNumberTagValue(SedonaVM* vm, Cell* params);

// void eacio.getStringTagValue(int, sys::Str, sys::Str)
Cell EacIo_eacio_getStringTagValue(SedonaVM* vm, Cell* params);

// int eacio.getTagType(int, sys::Str)
Cell EacIo_eacio_getTagType(SedonaVM* vm, Cell* params);

// int eacio.getLevel(int)
Cell EacIo_eacio_getLevel(SedonaVM* vm, Cell* params);

// float eacio.getLevelValue(int, int)
Cell EacIo_eacio_getLevelValue(SedonaVM* vm, Cell* params);

// int eacio.getChannelIn(int)
Cell EacIo_eacio_getChannelIn(SedonaVM* vm, Cell* params);

// float analogValuePoint.get(int)
Cell EacIo_analogValuePoint_get(SedonaVM* vm, Cell* params);

// native table for kit 4
NativeMethod kitNatives4[] = 
{
  NULL,                           // 4::0
  EacIo_boolInPoint_get,          // 4::1
  EacIo_boolOutPoint_set,         // 4::2
  EacIo_binaryValuePoint_set,     // 4::3
  EacIo_analogInPoint_get,        // 4::4
  EacIo_analogOutPoint_set,       // 4::5
  EacIo_analogValuePoint_set,     // 4::6
  EacIo_eacio_resolveChannel,     // 4::7
  EacIo_eacio_getRecordCount,     // 4::8
  EacIo_eacio_getCurStatus,       // 4::9
  EacIo_eacio_getChannelName,     // 4::10
  EacIo_triacPoint_set,           // 4::11
  EacIo_eacio_writeSedonaId,      // 4::12
  EacIo_eacio_writeSedonaType,    // 4::13
  EacIo_eacio_isChannelEnabled,   // 4::14
  EacIo_eacio_getBoolTagValue,    // 4::15
  EacIo_eacio_getNumberTagValue,  // 4::16
  EacIo_eacio_getStringTagValue,  // 4::17
  EacIo_eacio_getTagType,         // 4::18
  EacIo_eacio_getLevel,           // 4::19
  EacIo_eacio_getLevelValue,      // 4::20
  EacIo_eacio_getChannelIn,       // 4::21
  EacIo_analogValuePoint_get,     // 4::22
};

////////////////////////////////////////////////////////////////
// datetimeStd (kitId=9)
////////////////////////////////////////////////////////////////

// long DateTimeServiceStd.doNow()
Cell datetimeStd_DateTimeServiceStd_doNow(SedonaVM* vm, Cell* params);

// void DateTimeServiceStd.doSetClock(long)
Cell datetimeStd_DateTimeServiceStd_doSetClock(SedonaVM* vm, Cell* params);

// int DateTimeServiceStd.doGetUtcOffset()
Cell datetimeStd_DateTimeServiceStd_doGetUtcOffset(SedonaVM* vm, Cell* params);

// native table for kit 9
NativeMethod kitNatives9[] = 
{
  datetimeStd_DateTimeServiceStd_doNow,  // 9::0
  datetimeStd_DateTimeServiceStd_doSetClock,  // 9::1
  datetimeStd_DateTimeServiceStd_doGetUtcOffset,  // 9::2
};

////////////////////////////////////////////////////////////////
// shaystack (kitId=100)
////////////////////////////////////////////////////////////////

// sys::Obj HaystackDevice.open(sys::Str, sys::Str, sys::Str)
Cell shaystack_HaystackDevice_open(SedonaVM* vm, Cell* params);

// void HaystackDevice.call(sys::Obj, sys::Str)
Cell shaystack_HaystackDevice_call(SedonaVM* vm, Cell* params);

// float HaystackDevice.read_float(sys::Obj, sys::Str)
Cell shaystack_HaystackDevice_read_float(SedonaVM* vm, Cell* params);

// bool HaystackDevice.read_bool(sys::Obj, sys::Str)
Cell shaystack_HaystackDevice_read_bool(SedonaVM* vm, Cell* params);

// float HaystackDevice.eval_float(sys::Obj, sys::Str, int, sys::Str)
Cell shaystack_HaystackDevice_eval_float(SedonaVM* vm, Cell* params);

// bool HaystackDevice.eval_bool(sys::Obj, sys::Str, int, sys::Str)
Cell shaystack_HaystackDevice_eval_bool(SedonaVM* vm, Cell* params);

// sys::Obj HaystackDevice.create_client(sys::Str, sys::Str, sys::Str)
Cell shaystack_HaystackDevice_create_client(SedonaVM* vm, Cell* params);

// bool HaystackDevice.is_authenticated(sys::Obj)
Cell shaystack_HaystackDevice_is_authenticated(SedonaVM* vm, Cell* params);

// bool HaystackDevice.get_auth_message(sys::Obj, sys::Str, sys::Str, int)
Cell shaystack_HaystackDevice_get_auth_message(SedonaVM* vm, Cell* params);

// bool HaystackDevice.read_message(sys::Obj, sys::Str, sys::Str, int)
Cell shaystack_HaystackDevice_read_message(SedonaVM* vm, Cell* params);

// bool HaystackDevice.eval_message(sys::Obj, sys::Str, sys::Str, int)
Cell shaystack_HaystackDevice_eval_message(SedonaVM* vm, Cell* params);

// bool HaystackDevice.watch_sub_message(sys::Obj, sys::Str, sys::Str, sys::Str, sys::Str, int)
Cell shaystack_HaystackDevice_watch_sub_message(SedonaVM* vm, Cell* params);

// bool HaystackDevice.watch_unsub_message(sys::Obj, sys::Str, sys::Str, sys::Str, int)
Cell shaystack_HaystackDevice_watch_unsub_message(SedonaVM* vm, Cell* params);

// bool HaystackDevice.watch_poll_message(sys::Obj, sys::Str, sys::Str, int)
Cell shaystack_HaystackDevice_watch_poll_message(SedonaVM* vm, Cell* params);

// bool HaystackDevice.write_float_point_message(sys::Obj, sys::Str, int, float, int, sys::Str, int)
Cell shaystack_HaystackDevice_write_float_point_message(SedonaVM* vm, Cell* params);

// bool HaystackDevice.write_bool_point_message(sys::Obj, sys::Str, int, bool, int, sys::Str, int)
Cell shaystack_HaystackDevice_write_bool_point_message(SedonaVM* vm, Cell* params);

// bool HaystackDevice.write_read_point_message(sys::Obj, sys::Str, sys::Str, int)
Cell shaystack_HaystackDevice_write_read_point_message(SedonaVM* vm, Cell* params);

// bool HaystackDevice.reset_point_message(sys::Obj, sys::Str, int, sys::Str, int)
Cell shaystack_HaystackDevice_reset_point_message(SedonaVM* vm, Cell* params);

// bool HaystackDevice.is_empty(byte[])
Cell shaystack_HaystackDevice_is_empty(SedonaVM* vm, Cell* params);

// bool HaystackDevice.is_err(byte[])
Cell shaystack_HaystackDevice_is_err(SedonaVM* vm, Cell* params);

// bool HaystackDevice.has_float(byte[], int, sys::Str)
Cell shaystack_HaystackDevice_has_float(SedonaVM* vm, Cell* params);

// bool HaystackDevice.has_bool(byte[], int, sys::Str)
Cell shaystack_HaystackDevice_has_bool(SedonaVM* vm, Cell* params);

// bool HaystackDevice.parse_bool_response(byte[], int, sys::Str)
Cell shaystack_HaystackDevice_parse_bool_response(SedonaVM* vm, Cell* params);

// float HaystackDevice.parse_float_response(byte[], int, sys::Str, sys::Obj)
Cell shaystack_HaystackDevice_parse_float_response(SedonaVM* vm, Cell* params);

// bool HaystackDevice.parse_str_response(byte[], int, sys::Str, bool, sys::Str, int)
Cell shaystack_HaystackDevice_parse_str_response(SedonaVM* vm, Cell* params);

// bool HaystackDevice.is_filter_valid(sys::Str)
Cell shaystack_HaystackDevice_is_filter_valid(SedonaVM* vm, Cell* params);

// void HaystackDevice.delete_client(sys::Obj)
Cell shaystack_HaystackDevice_delete_client(SedonaVM* vm, Cell* params);

// bool HaystackDevice.isSessionConnected(sys::Obj)
Cell shaystack_HaystackDevice_isSessionConnected(SedonaVM* vm, Cell* params);

// native table for kit 100
NativeMethod kitNatives100[] = 
{
  shaystack_HaystackDevice_open,  // 100::0
  shaystack_HaystackDevice_call,  // 100::1
  shaystack_HaystackDevice_read_float,  // 100::2
  shaystack_HaystackDevice_read_bool,  // 100::3
  shaystack_HaystackDevice_eval_float,  // 100::4
  shaystack_HaystackDevice_eval_bool,  // 100::5
  shaystack_HaystackDevice_create_client,  // 100::6
  shaystack_HaystackDevice_is_authenticated,  // 100::7
  shaystack_HaystackDevice_get_auth_message,  // 100::8
  shaystack_HaystackDevice_read_message,  // 100::9
  shaystack_HaystackDevice_eval_message,  // 100::10
  shaystack_HaystackDevice_watch_sub_message,  // 100::11
  shaystack_HaystackDevice_watch_unsub_message,  // 100::12
  shaystack_HaystackDevice_watch_poll_message,  // 100::13
  shaystack_HaystackDevice_write_float_point_message,  // 100::14
  shaystack_HaystackDevice_write_bool_point_message,  // 100::15
  shaystack_HaystackDevice_write_read_point_message,  // 100::16
  shaystack_HaystackDevice_reset_point_message,  // 100::17
  shaystack_HaystackDevice_is_empty,  // 100::18
  shaystack_HaystackDevice_is_err,  // 100::19
  shaystack_HaystackDevice_has_float,  // 100::20
  shaystack_HaystackDevice_has_bool,  // 100::21
  shaystack_HaystackDevice_parse_bool_response,  // 100::22
  shaystack_HaystackDevice_parse_float_response,  // 100::23
  shaystack_HaystackDevice_parse_str_response,  // 100::24
  shaystack_HaystackDevice_is_filter_valid,  // 100::25
  shaystack_HaystackDevice_delete_client,  // 100::26
  shaystack_HaystackDevice_isSessionConnected,  // 100::27
};

////////////////////////////////////////////////////////////////
// Native Table
////////////////////////////////////////////////////////////////

NativeMethod* nativeTable[] = 
{
  kitNatives0,     // 0
  NULL,            // 1
  kitNatives2,     // 2
  NULL,            // 3
  kitNatives4,     // 4
  NULL,            // 5
  NULL,            // 6
  NULL,            // 7
  NULL,            // 8
  kitNatives9,     // 9
  NULL,            // 10
  NULL,            // 11
  NULL,            // 12
  NULL,            // 13
  NULL,            // 14
  NULL,            // 15
  NULL,            // 16
  NULL,            // 17
  NULL,            // 18
  NULL,            // 19
  NULL,            // 20
  NULL,            // 21
  NULL,            // 22
  NULL,            // 23
  NULL,            // 24
  NULL,            // 25
  NULL,            // 26
  NULL,            // 27
  NULL,            // 28
  NULL,            // 29
  NULL,            // 30
  NULL,            // 31
  NULL,            // 32
  NULL,            // 33
  NULL,            // 34
  NULL,            // 35
  NULL,            // 36
  NULL,            // 37
  NULL,            // 38
  NULL,            // 39
  NULL,            // 40
  NULL,            // 41
  NULL,            // 42
  NULL,            // 43
  NULL,            // 44
  NULL,            // 45
  NULL,            // 46
  NULL,            // 47
  NULL,            // 48
  NULL,            // 49
  NULL,            // 50
  NULL,            // 51
  NULL,            // 52
  NULL,            // 53
  NULL,            // 54
  NULL,            // 55
  NULL,            // 56
  NULL,            // 57
  NULL,            // 58
  NULL,            // 59
  NULL,            // 60
  NULL,            // 61
  NULL,            // 62
  NULL,            // 63
  NULL,            // 64
  NULL,            // 65
  NULL,            // 66
  NULL,            // 67
  NULL,            // 68
  NULL,            // 69
  NULL,            // 70
  NULL,            // 71
  NULL,            // 72
  NULL,            // 73
  NULL,            // 74
  NULL,            // 75
  NULL,            // 76
  NULL,            // 77
  NULL,            // 78
  NULL,            // 79
  NULL,            // 80
  NULL,            // 81
  NULL,            // 82
  NULL,            // 83
  NULL,            // 84
  NULL,            // 85
  NULL,            // 86
  NULL,            // 87
  NULL,            // 88
  NULL,            // 89
  NULL,            // 90
  NULL,            // 91
  NULL,            // 92
  NULL,            // 93
  NULL,            // 94
  NULL,            // 95
  NULL,            // 96
  NULL,            // 97
  NULL,            // 98
  NULL,            // 99
  kitNatives100,   // 100
};

////////////////////////////////////////////////////////////////
// Native Id Check
////////////////////////////////////////////////////////////////

#ifdef SCODE_DEBUG
int isNativeIdValid(int kitId, int methodId)
{
  switch(kitId)
  {
    case 0:
      if (methodId >= 60) return 0;
      else return kitNatives0[methodId] != NULL;
    case 2:
      if (methodId >= 17) return 0;
      else return kitNatives2[methodId] != NULL;
    case 4:
      if (methodId >= 23) return 0;
      else return kitNatives4[methodId] != NULL;
    case 9:
      if (methodId >= 3) return 0;
      else return kitNatives9[methodId] != NULL;
    case 100:
      if (methodId >= 28) return 0;
      else return kitNatives100[methodId] != NULL;
    default:
       return 0;
  }
}
#endif


