//! Scode image file loader with header validation.
//!
//! The `.scode` file format is generated by the Sedona compiler (sedonac).
//! It uses the **native endian** of the target platform. Since our targets
//! (BeagleBone ARM and x86 Windows/Linux) are all little-endian, we read
//! multi-byte values as little-endian.
//!
//! # Header Layout (32 bytes)
//!
//! | Offset | Size | Field           | Description                          |
//! |--------|------|-----------------|--------------------------------------|
//! | 0      | 4    | magic           | 0x5ED0BA07 (also validates endian)   |
//! | 4      | 1    | major_ver       | Must be 0x01                         |
//! | 5      | 1    | minor_ver       | Must be 0x05                         |
//! | 6      | 1    | block_size      | Sedona block size (always 4)         |
//! | 7      | 1    | ref_size        | Pointer size (4 for 32-bit)          |
//! | 8      | 4    | image_size      | Total scode file size in bytes       |
//! | 12     | 4    | data_size       | Static data segment size (malloc'd)  |
//! | 16     | 2    | main_method     | Block index of main entry method     |
//! | 18     | 2    | tests_bix       | Block index of test table (0=none)   |
//! | 20     | 4    | reserved_a      | Reserved (used by Java toolchain)    |
//! | 24     | 2    | resume_method   | Block index of resume entry method   |
//! | 26     | 2    | reserved_b      | Reserved                             |
//! | 28     | 4    | reserved_c      | Reserved                             |

use crate::vm_error::VmError;
use std::path::Path;

/// Expected magic number: 0x5ED0BA07 ("SEDOBA07")
pub const SCODE_MAGIC: u32 = 0x5ED0_BA07;

/// Expected major version
pub const SCODE_MAJOR_VER: u8 = 0x01;

/// Expected minor version
pub const SCODE_MINOR_VER: u8 = 0x05;

/// Standard Sedona block size in bytes
pub const SCODE_BLOCK_SIZE: u8 = 4;

/// Minimum header size in bytes
pub const SCODE_HEADER_SIZE: usize = 32;

/// Parsed scode file header.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScodeHeader {
    /// Magic number — must be `0x5ED0BA07`
    pub magic: u32,
    /// Major version — must be 1
    pub major_ver: u8,
    /// Minor version — must be 5
    pub minor_ver: u8,
    /// Block size in bytes (always 4)
    pub block_size: u8,
    /// Reference/pointer size (4 for 32-bit targets)
    pub ref_size: u8,
    /// Total image (file) size in bytes
    pub image_size: u32,
    /// Static data segment size in bytes
    pub data_size: u32,
    /// Block index of the main entry method
    pub main_method: u16,
    /// Block index of the test table (0 = no tests)
    pub tests_bix: u16,
    /// Block index of the resume entry method
    pub resume_method: u16,
}

impl ScodeHeader {
    /// Parse the header from the first [`SCODE_HEADER_SIZE`] bytes.
    ///
    /// Returns `Err(VmError::BadImage)` if the data is too short.
    pub fn parse(data: &[u8]) -> Result<Self, VmError> {
        if data.len() < SCODE_HEADER_SIZE {
            return Err(VmError::BadImage(format!(
                "scode too short for header: {} bytes (need at least {})",
                data.len(),
                SCODE_HEADER_SIZE,
            )));
        }

        let magic = u32::from_le_bytes([data[0], data[1], data[2], data[3]]);
        let major_ver = data[4];
        let minor_ver = data[5];
        let block_size = data[6];
        let ref_size = data[7];
        let image_size = u32::from_le_bytes([data[8], data[9], data[10], data[11]]);
        let data_size = u32::from_le_bytes([data[12], data[13], data[14], data[15]]);
        let main_method = u16::from_le_bytes([data[16], data[17]]);
        let tests_bix = u16::from_le_bytes([data[18], data[19]]);
        let resume_method = u16::from_le_bytes([data[24], data[25]]);

        Ok(ScodeHeader {
            magic,
            major_ver,
            minor_ver,
            block_size,
            ref_size,
            image_size,
            data_size,
            main_method,
            tests_bix,
            resume_method,
        })
    }

    /// Validate the header fields.
    ///
    /// Checks magic number, version, block size, and that the image size
    /// is at least as large as the header.
    pub fn validate(&self) -> Result<(), VmError> {
        if self.magic != SCODE_MAGIC {
            return Err(VmError::BadImage(format!(
                "bad magic: expected 0x{:08X}, got 0x{:08X}",
                SCODE_MAGIC, self.magic,
            )));
        }

        if self.major_ver != SCODE_MAJOR_VER || self.minor_ver != SCODE_MINOR_VER {
            return Err(VmError::BadImage(format!(
                "unsupported version: {}.{} (expected {}.{})",
                self.major_ver, self.minor_ver, SCODE_MAJOR_VER, SCODE_MINOR_VER,
            )));
        }

        if self.block_size != SCODE_BLOCK_SIZE {
            return Err(VmError::BadImage(format!(
                "bad block size: expected {}, got {}",
                SCODE_BLOCK_SIZE, self.block_size,
            )));
        }

        if (self.image_size as usize) < SCODE_HEADER_SIZE {
            return Err(VmError::BadImage(format!(
                "image_size {} is smaller than header ({})",
                self.image_size, SCODE_HEADER_SIZE,
            )));
        }

        Ok(())
    }

    /// Validate header and also check that the actual data length matches.
    pub fn validate_with_length(&self, actual_len: usize) -> Result<(), VmError> {
        self.validate()?;

        if actual_len != self.image_size as usize {
            return Err(VmError::BadImage(format!(
                "image_size mismatch: header says {} bytes, actual data is {} bytes",
                self.image_size, actual_len,
            )));
        }

        Ok(())
    }
}

/// A loaded scode image ready for VM execution.
#[derive(Debug, Clone)]
pub struct ScodeImage {
    /// Parsed and validated header
    pub header: ScodeHeader,
    /// Raw scode bytes (the entire file contents)
    pub code: Vec<u8>,
}

impl ScodeImage {
    /// Load a `.scode` file from disk.
    pub fn load_from_file(path: &Path) -> Result<Self, VmError> {
        let data = std::fs::read(path).map_err(|e| {
            VmError::BadImage(format!("failed to read {}: {}", path.display(), e))
        })?;
        Self::load_from_bytes(&data)
    }

    /// Load from a byte slice (useful for testing or embedded images).
    pub fn load_from_bytes(data: &[u8]) -> Result<Self, VmError> {
        let header = ScodeHeader::parse(data)?;
        header.validate_with_length(data.len())?;

        Ok(ScodeImage {
            header,
            code: data.to_vec(),
        })
    }

    /// Get a single byte at an absolute offset.
    #[inline]
    pub fn get_u8(&self, offset: usize) -> Option<u8> {
        self.code.get(offset).copied()
    }

    /// Get a little-endian `u16` at an absolute byte offset.
    #[inline]
    pub fn get_u16(&self, offset: usize) -> Option<u16> {
        let slice = self.code.get(offset..offset + 2)?;
        Some(u16::from_le_bytes([slice[0], slice[1]]))
    }

    /// Get a little-endian `u32` at an absolute byte offset.
    #[inline]
    pub fn get_u32(&self, offset: usize) -> Option<u32> {
        let slice = self.code.get(offset..offset + 4)?;
        Some(u32::from_le_bytes([slice[0], slice[1], slice[2], slice[3]]))
    }

    /// Get a little-endian `i32` at an absolute byte offset.
    #[inline]
    pub fn get_i32(&self, offset: usize) -> Option<i32> {
        self.get_u32(offset).map(|v| v as i32)
    }

    /// Get a little-endian `u64` at an absolute byte offset.
    #[inline]
    pub fn get_u64(&self, offset: usize) -> Option<u64> {
        let slice = self.code.get(offset..offset + 8)?;
        Some(u64::from_le_bytes([
            slice[0], slice[1], slice[2], slice[3],
            slice[4], slice[5], slice[6], slice[7],
        ]))
    }

    /// Convert a block index to a byte offset: `block * block_size`.
    #[inline]
    pub fn block_to_offset(&self, block: u16) -> usize {
        (block as usize) * (self.header.block_size as usize)
    }

    /// Total image length in bytes.
    #[inline]
    pub fn len(&self) -> usize {
        self.code.len()
    }

    /// Whether the image is empty (should never be true after successful load).
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.code.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a minimal valid scode header + padding to `image_size` bytes.
    fn make_valid_scode(image_size: u32) -> Vec<u8> {
        let mut buf = vec![0u8; image_size as usize];
        // magic (LE)
        buf[0..4].copy_from_slice(&SCODE_MAGIC.to_le_bytes());
        // version
        buf[4] = SCODE_MAJOR_VER;
        buf[5] = SCODE_MINOR_VER;
        // block size
        buf[6] = SCODE_BLOCK_SIZE;
        // ref size (4 = 32-bit)
        buf[7] = 4;
        // image_size (LE)
        buf[8..12].copy_from_slice(&image_size.to_le_bytes());
        // data_size = 64 bytes
        buf[12..16].copy_from_slice(&64u32.to_le_bytes());
        // main_method = block 7
        buf[16..18].copy_from_slice(&7u16.to_le_bytes());
        // tests_bix = 0 (no tests)
        buf[18..20].copy_from_slice(&0u16.to_le_bytes());
        // resume_method = block 12
        buf[24..26].copy_from_slice(&12u16.to_le_bytes());
        buf
    }

    #[test]
    fn parse_valid_header() {
        let data = make_valid_scode(128);
        let header = ScodeHeader::parse(&data).expect("parse failed");
        assert_eq!(header.magic, SCODE_MAGIC);
        assert_eq!(header.major_ver, 1);
        assert_eq!(header.minor_ver, 5);
        assert_eq!(header.block_size, 4);
        assert_eq!(header.ref_size, 4);
        assert_eq!(header.image_size, 128);
        assert_eq!(header.data_size, 64);
        assert_eq!(header.main_method, 7);
        assert_eq!(header.tests_bix, 0);
        assert_eq!(header.resume_method, 12);
    }

    #[test]
    fn validate_valid_header() {
        let data = make_valid_scode(128);
        let header = ScodeHeader::parse(&data).unwrap();
        header.validate().expect("validate should succeed");
    }

    #[test]
    fn reject_invalid_magic() {
        let mut data = make_valid_scode(128);
        data[0] = 0xFF; // corrupt magic
        let header = ScodeHeader::parse(&data).unwrap();
        let err = header.validate().unwrap_err();
        match err {
            VmError::BadImage(msg) => assert!(msg.contains("bad magic"), "got: {msg}"),
            other => panic!("expected BadImage, got: {other:?}"),
        }
    }

    #[test]
    fn reject_bad_version() {
        let mut data = make_valid_scode(128);
        data[4] = 0x02; // major version 2
        let header = ScodeHeader::parse(&data).unwrap();
        let err = header.validate().unwrap_err();
        match err {
            VmError::BadImage(msg) => assert!(msg.contains("version"), "got: {msg}"),
            other => panic!("expected BadImage, got: {other:?}"),
        }
    }

    #[test]
    fn reject_bad_block_size() {
        let mut data = make_valid_scode(128);
        data[6] = 8; // wrong block size
        let header = ScodeHeader::parse(&data).unwrap();
        let err = header.validate().unwrap_err();
        match err {
            VmError::BadImage(msg) => assert!(msg.contains("block size"), "got: {msg}"),
            other => panic!("expected BadImage, got: {other:?}"),
        }
    }

    #[test]
    fn reject_truncated_data() {
        let data = vec![0u8; 16]; // too short for header
        let err = ScodeHeader::parse(&data).unwrap_err();
        match err {
            VmError::BadImage(msg) => assert!(msg.contains("too short"), "got: {msg}"),
            other => panic!("expected BadImage, got: {other:?}"),
        }
    }

    #[test]
    fn reject_size_mismatch() {
        let data = make_valid_scode(128);
        let header = ScodeHeader::parse(&data).unwrap();
        // Pretend actual length is different
        let err = header.validate_with_length(256).unwrap_err();
        match err {
            VmError::BadImage(msg) => assert!(msg.contains("mismatch"), "got: {msg}"),
            other => panic!("expected BadImage, got: {other:?}"),
        }
    }

    #[test]
    fn load_from_bytes_valid() {
        let data = make_valid_scode(128);
        let image = ScodeImage::load_from_bytes(&data).expect("load failed");
        assert_eq!(image.len(), 128);
        assert!(!image.is_empty());
        assert_eq!(image.header.main_method, 7);
    }

    #[test]
    fn load_from_bytes_rejects_bad_magic() {
        let mut data = make_valid_scode(128);
        data[0] = 0x00;
        let err = ScodeImage::load_from_bytes(&data).unwrap_err();
        assert!(matches!(err, VmError::BadImage(_)));
    }

    #[test]
    fn block_to_offset_conversion() {
        let data = make_valid_scode(128);
        let image = ScodeImage::load_from_bytes(&data).unwrap();
        assert_eq!(image.block_to_offset(0), 0);
        assert_eq!(image.block_to_offset(1), 4);
        assert_eq!(image.block_to_offset(7), 28);
        assert_eq!(image.block_to_offset(100), 400);
        assert_eq!(image.block_to_offset(0xFFFF), 65535 * 4);
    }

    #[test]
    fn get_u8_in_bounds() {
        let data = make_valid_scode(128);
        let image = ScodeImage::load_from_bytes(&data).unwrap();
        assert_eq!(image.get_u8(4), Some(SCODE_MAJOR_VER));
        assert_eq!(image.get_u8(5), Some(SCODE_MINOR_VER));
    }

    #[test]
    fn get_u8_out_of_bounds() {
        let data = make_valid_scode(32);
        let image = ScodeImage::load_from_bytes(&data).unwrap();
        assert_eq!(image.get_u8(32), None);
        assert_eq!(image.get_u8(1000), None);
    }

    #[test]
    fn get_u16_little_endian() {
        let mut data = make_valid_scode(128);
        // Write 0x1234 at offset 40 (LE: 0x34, 0x12)
        data[40] = 0x34;
        data[41] = 0x12;
        let image = ScodeImage::load_from_bytes(&data).unwrap();
        assert_eq!(image.get_u16(40), Some(0x1234));
    }

    #[test]
    fn get_u16_out_of_bounds() {
        let data = make_valid_scode(32);
        let image = ScodeImage::load_from_bytes(&data).unwrap();
        assert_eq!(image.get_u16(31), None);
        assert_eq!(image.get_u16(32), None);
    }

    #[test]
    fn get_u32_little_endian() {
        let data = make_valid_scode(128);
        let image = ScodeImage::load_from_bytes(&data).unwrap();
        assert_eq!(image.get_u32(0), Some(SCODE_MAGIC));
        assert_eq!(image.get_u32(8), Some(128));
    }

    #[test]
    fn get_u32_out_of_bounds() {
        let data = make_valid_scode(32);
        let image = ScodeImage::load_from_bytes(&data).unwrap();
        assert_eq!(image.get_u32(29), None);
        assert_eq!(image.get_u32(32), None);
    }

    #[test]
    fn get_i32_reads_signed() {
        let mut data = make_valid_scode(128);
        data[40..44].copy_from_slice(&(-1i32).to_le_bytes());
        let image = ScodeImage::load_from_bytes(&data).unwrap();
        assert_eq!(image.get_i32(40), Some(-1));
    }

    #[test]
    fn get_u64_little_endian() {
        let mut data = make_valid_scode(128);
        let val: u64 = 0x0102_0304_0506_0708;
        data[40..48].copy_from_slice(&val.to_le_bytes());
        let image = ScodeImage::load_from_bytes(&data).unwrap();
        assert_eq!(image.get_u64(40), Some(val));
    }

    #[test]
    fn load_from_file_nonexistent() {
        let err = ScodeImage::load_from_file(Path::new("/nonexistent/kits.scode")).unwrap_err();
        match err {
            VmError::BadImage(msg) => assert!(msg.contains("failed to read"), "got: {msg}"),
            other => panic!("expected BadImage, got: {other:?}"),
        }
    }
}
